# Generated by Django 6.0.1 on 2026-01-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
